#bawimy się :)
print('czas co s fajnego ogarnąc')
myName = input()
print('czas '+myName+ ' zrobic cos konstruktywnego')
print('dlugosc imienia to: ')
print(len(myName))
print('Twoj wiek?')
myAge = input()
print('bedziesz mial ' + str(int(myAge) + 1) + ' za rok')

